name: release
on:
  push:
    tags: ["*.*.*.*"]
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.100
      - uses: actions/checkout@v3.3.0
      - env:
          MINVER_VERSION: ${{ github.ref_name }}
        run: ./build build
      - name: push
        env:
          SOURCE: nuget.org
          API_KEY: ${{ secrets.NUGET_PUSH_API_KEY }}
        if: env.SOURCE != '' || env.API_KEY != ''
        run: dotnet nuget push ./MinVer/bin/Release/*.nupkg --source ${{ env.SOURCE }} --api-key ${{ env.API_KEY }}
